development:
  adapter: mysql2
  dataserver: localhost
  database: bookworms_dev
  username: root
  password: 
  
test:
  adapter: mysql2
  dataserver: localhost
  database: bookworms_test
  username: root
  password: 
  